// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6W9hfvn93PyVKDpOtKg9GS6CQHvjTmE',
    appId: '1:82419508135:web:86dfb1794d618ddc784c82',
    messagingSenderId: '82419508135',
    projectId: 'ecommerce-app-3009e',
    authDomain: 'ecommerce-app-3009e.firebaseapp.com',
    storageBucket: 'ecommerce-app-3009e.appspot.com',
    measurementId: 'G-FVM61ZQF4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0M885sSamBQR03QNWhFmXF0coyGwMFCk',
    appId: '1:82419508135:android:cb53049117cba1d1784c82',
    messagingSenderId: '82419508135',
    projectId: 'ecommerce-app-3009e',
    storageBucket: 'ecommerce-app-3009e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiwlW7NK9X8QXm48j-AZpxZo0k-UwhG9A',
    appId: '1:82419508135:ios:38adc332780f7657784c82',
    messagingSenderId: '82419508135',
    projectId: 'ecommerce-app-3009e',
    storageBucket: 'ecommerce-app-3009e.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
